import type { DiscoverResponse, GameGuideResponse, GameRecommendation, GuidePhase } from "../src/types.js";
type Game = Omit<GameRecommendation,"match"|"why"|"watchOut"> & { aliases:string[]; signals:string[]; why:string; watchOut:string; tips:string[] };
const s=(id:string)=>"https://store.steampowered.com/app/"+id+"/";
export const catalog:Game[]=[
{id:"outer-wilds",title:"Outer Wilds",year:2019,genres:["探索","叙事"],tags:["科幻","时间循环","考古"],platforms:["PC","Xbox","PlayStation","Switch"],playtime:"12–20 小时",sourceUrl:s("753640"),aliases:["outer wilds","星际拓荒"],signals:["探索","未知","科幻","谜题","叙事","宇宙"],why:"把好奇心本身做成推进力，线索会组成漂亮的知识网络。",watchOut:"几乎没有传统数值成长，需要接受自己变强的方式是理解世界。",tips:["看到异常先记录位置和关键词，不要急着查攻略。","把不同星球当作一张互相解释的线索网。"]},
{id:"against-the-storm",title:"Against the Storm",year:2023,genres:["策略","经营"],tags:["肉鸽","城市建造","短局"],platforms:["PC"],playtime:"每局 30–90 分钟",sourceUrl:s("1336490"),aliases:["against the storm","风暴之城"],signals:["策略","规划","经营","短局","重玩","资源"],why:"每局都有新约束，规划密度高但不拖沓。",watchOut:"系统层次多，前几局需要时间建立资源优先级。",tips:["先满足生存和决心，再追求漂亮的生产链。","把声望看作最重要的节奏指标。"]},
{id:"dredge",title:"DREDGE",year:2023,genres:["冒险","钓鱼"],tags:["克苏鲁","轻经营","短流程"],platforms:["PC","Xbox","PlayStation","Switch"],playtime:"10–15 小时",sourceUrl:s("1562430"),aliases:["dredge","渔帆暗涌"],signals:["克苏鲁","恐怖","钓鱼","经营","短","氛围","探索"],why:"白天经营、夜晚冒险的节奏清晰，轻度恐怖与收集探索结合得很顺。",watchOut:"夜间航行会逐渐紧张，完全不喜欢压迫感的话体验可能打折。",tips:["优先升级船舱和引擎，让每次出航更有余裕。","不要贪最后一条鱼，安全返航本身就是收益。"]},
{id:"baldurs-gate-3",title:"Baldur’s Gate 3",year:2023,genres:["RPG","回合制"],tags:["剧情","角色","选择"],platforms:["PC","Xbox","PlayStation"],playtime:"80–150 小时",sourceUrl:s("1086940"),aliases:["baldur's gate 3","博德之门3","博德之门 3"],signals:["剧情","角色","选择","回合制","rpg","队友","自由"],why:"选择真实改变关系和局势，战斗鼓励利用环境和临场创意。",watchOut:"内容体量很大，想看全支线会显著拉长时间。",tips:["把队友当作不同解法，而不是只看战斗数值。","长休不仅是回复资源，也是推进角色剧情的重要动作。"]},
{id:"elden-ring",title:"Elden Ring",year:2022,genres:["动作 RPG","开放世界"],tags:["高难度","探索","构筑"],platforms:["PC","Xbox","PlayStation"],playtime:"60–120 小时",sourceUrl:s("1245620"),aliases:["elden ring","艾尔登法环"],signals:["高难度","挑战","动作","开放世界","探索","boss","构筑"],why:"探索、战斗和构筑互相喂养，失败成本可控。",watchOut:"前期信息密度和地图尺度都很高，不必把每个区域一次清空。",tips:["打不过就离开、升级、换武器或换路线。","把升级点投入一条清晰的主属性，先保证生存。"]},
{id:"hades",title:"Hades",year:2020,genres:["动作","肉鸽"],tags:["短局","剧情","构筑"],platforms:["PC","Xbox","PlayStation","Switch"],playtime:"20–40 小时",sourceUrl:s("1145360"),aliases:["hades","哈迪斯"],signals:["短局","重玩","动作","剧情","肉鸽","构筑"],why:"每次失败都推进叙事，重复游玩很有意义。",watchOut:"它围绕重复构建节奏，和一次性通关的期待不同。",tips:["前期优先解锁稳定的镜子能力。","每次回城都和角色对话，剧情本来就是奖励的一部分。"]},
{id:"balatro",title:"Balatro",year:2024,genres:["卡牌","肉鸽"],tags:["短局","构筑","高重玩"],platforms:["PC","Xbox","PlayStation","Switch","Mobile"],playtime:"每局 20–45 分钟",sourceUrl:s("2379780"),aliases:["balatro","小丑牌"],signals:["卡牌","构筑","短局","重玩","数字","策略"],why:"规则简单但组合空间极深，每局都能快速验证新想法。",watchOut:"数值滚雪球后很容易一不小心玩到深夜。",tips:["先稳定倍率和筹码，再考虑极端的单一流派。","商店刷新要服务当前牌组。"]},
{id:"stardew-valley",title:"Stardew Valley",year:2016,genres:["经营","生活模拟"],tags:["治愈","种田","关系"],platforms:["PC","Xbox","PlayStation","Switch","Mobile"],playtime:"40–100 小时",sourceUrl:s("413150"),aliases:["stardew valley","星露谷物语","星露谷"],signals:["治愈","轻松","种田","经营","关系","生活","联机"],why:"目标可以自己定义，日常节奏松弛，探索和关系经营互相补充。",watchOut:"季节和时间会给人轻微规划压力，但不需要追求完美。",tips:["第一年优先扩充背包和稳定收入。","留一份常见物品库存，社区中心会用到。"]},
{id:"factorio",title:"Factorio",year:2020,genres:["自动化","策略"],tags:["生产链","规划","优化"],platforms:["PC"],playtime:"50–200 小时",sourceUrl:s("427520"),aliases:["factorio","异星工厂"],signals:["自动化","生产","规划","优化","工厂","策略"],why:"每个问题都能通过系统设计解决，从手工到自动化成长感扎实。",watchOut:"自由度带来很强的沉浸性，最好提前给自己设定停机时间。",tips:["先保证物流畅通，再追求工厂布局美观。","把瓶颈当作下一步研究目标。"]},
{id:"disco-elysium",title:"Disco Elysium",year:2019,genres:["叙事 RPG","侦探"],tags:["文字","角色","政治"],platforms:["PC","Xbox","PlayStation","Switch"],playtime:"20–35 小时",sourceUrl:s("632470"),aliases:["disco elysium","极乐迪斯科"],signals:["剧情","文字","角色","侦探","对话","沉浸"],why:"把内心声音变成真正的角色阵容，失败也常常打开另一条路。",watchOut:"阅读量很大，战斗不是核心，适合愿意慢慢读的人。",tips:["不要害怕失败，技能检定失败经常会打开另一条路。","选择一个有趣的性格方向，比追求万能更有记忆点。"]}
];
const pref:Record<string,string[]>={"剧情与角色":["剧情","角色","叙事","对话","选择"],"策略与规划":["策略","规划","资源","生产","管理","优化"],"探索未知":["探索","未知","科幻","宇宙","地图"],"短局高重玩":["短局","重玩","肉鸽","构筑"],"合作游玩":["联机","合作","多人","队友"],"轻松治愈":["治愈","轻松","生活","种田","经营"],"高难度挑战":["高难度","挑战","boss","动作"],"卡牌与构筑":["卡牌","构筑","爬塔"],"恐怖或克苏鲁":["克苏鲁","恐怖","氛围"],"科幻题材":["科幻","宇宙"]};
const norm=(s:string)=>s.toLowerCase();
export function interpretPrompt(prompt:string){const text=norm(prompt); const labels=Object.entries(pref).filter(([,terms])=>terms.some(t=>text.includes(t))).map(([label])=>label); return labels.length?labels:["开放探索","重视体验感"];}
export function findCatalogGame(name:string){const q=norm(name.trim()); return catalog.find(g=>g.aliases.some(a=>q.includes(a)||a.includes(q)))||catalog[0];}
function score(g:Game,prompt:string){const t=norm(prompt); const hits=g.signals.filter(x=>t.includes(x)).length; let value=58+hits*10; if(/短|不长/.test(t)&&g.tags.some(x=>x.includes("短"))) value+=12; return Math.min(97,value);}
export function discoverFromCatalog(prompt:string):DiscoverResponse{const prefs=interpretPrompt(prompt); const games=catalog.map(g=>({id:g.id,title:g.title,year:g.year,genres:g.genres,tags:g.tags,platforms:g.platforms,playtime:g.playtime,sourceUrl:g.sourceUrl,officialUrl:"",match:score(g,prompt),why:g.why,watchOut:g.watchOut})).sort((a,b)=>b.match-a.match).slice(0,6); return {mode:"demo",summary:prompt.trim()?"根据“"+prompt.trim()+"”，推荐重心放在"+prefs.slice(0,3).join("、")+"。":"先从一组兼顾探索、节奏和成长感的游戏开始。",interpretedPreferences:prefs,games,sources:games.slice(0,4).map(g=>({title:g.title+" · Steam 商店页",url:g.sourceUrl})),note:"当前使用本地可解释目录。配置 OPENAI_API_KEY 后，服务端会自动切换到联网研究并保留来源。"};}
const tips:Record<string,string[]>={"elden ring":["前期把升级点优先放在生命值与一条主输出属性上。","遇到卡关先探索别处，护符、骨灰、战技和升级材料都能改变难度。"],"baldur's gate 3":["让队友参与长休和对话，很多关键线索不会出现在战斗里。","先观察环境再开战：高处、油桶、推拉和控制往往比面板伤害重要。"],"hades":["镜子里的稳定增益优先于追求一次性的炫技组合。","把每次失败当作收集信息和推进关系的完整回合。"],"balatro":["牌组越薄越容易找到核心组合，商店不是越多越好。","建立稳定倍率来源后，再补筹码、倍率或触发频率。"]};
export function guideFromCatalog(name:string,goal?:string):GameGuideResponse{const g=findCatalogGame(name); const advice=tips[g.aliases[0]]||g.tips; const phases:GuidePhase[]=[{title:"第一阶段 · 建立节奏",goal:"理解核心循环，不急着追求效率。",steps:["先完成“"+g.title+"”最短的一轮核心循环，确认资源、风险和回报。",advice[0],"记录两个让你卡住的地方，把它们留到下一轮解决。"]},{title:"第二阶段 · 形成路线",goal:"把一次成功拆解成可复用的决策。",steps:["围绕一个明确目标选择升级、路线或队伍，不要同时优化所有系统。",advice[1],"局面变差时先保住可持续性，而不是追求一次完美操作。"]},{title:"第三阶段 · 个性化优化",goal:"根据自己的偏好选择更深的挑战。",steps:["选择一条喜欢的流派或玩法分支，连续尝试三次再评价。","回看资源是否真正服务目标，删掉看似强但不稳定的选择。",goal?"围绕你的目标“"+goal+"”设一个可验证的完成条件。":"为下一次游玩写下一个小而具体的实验。"]}]; return {mode:"demo",game:g.title,overview:g.title+" 的乐趣在于"+g.why+" 这份路线按“先理解、再稳定、最后优化”的顺序安排。",difficulty:g.tags.includes("高难度")?"中高压，允许绕路解决":"中等，学习成本主要来自系统理解",estimatedMastery:g.playtime,coreLoop:["完成一轮最短的核心循环，观察输入、决策、风险与回报如何连接。","先识别当前阶段最重要的资源，再决定探索、战斗、建设或推进的顺序。","用一次失败找出一个可修正的变量，不要同时改动整套打法。","把有效选择重复三次，确认它是稳定方法而不是偶然成功。"],firstSession:["先完成必要的新手引导，遇到不懂的系统先记下关键词，不要立刻查所有细节。","用前 15 分钟确认移动、交互、战斗或主要操作的手感与快捷键。","完成一轮低风险目标，记录资源从哪里来、花在哪里、何时会断档。","选择一个简单方向作为本次主线，只学习会直接服务它的系统。","第一次受挫时先退一步观察替代路线，再决定是否需要重开。","结束第一小时后写下一个下次只验证一件事的小目标。"],phases,builds:[{name:"稳健入门",bestFor:"第一次接触或希望降低认知负担",priorities:["优先稳定收益","保留恢复和撤退余地","只使用一条主线升级"]},{name:"主动实验",bestFor:"已经理解循环，想提高上限",priorities:["围绕一个核心机制构筑","接受短期风险换取长期收益","用复盘替代盲目重开"]}],practicePlan:["连续三次游玩只练一个基础动作或决策，比较结果而不是比较输赢。","每次结束记录一个有效选择、一个失误和一个下次实验。","遇到卡关先改变路线、资源分配或节奏，再考虑照抄攻略。","把新系统分成“现在必须懂、稍后再懂、可以忽略”三档。","当入门路线稳定后，再选择一个与自己目标一致的进阶方向。"],mistakes:["把所有收集/支线都当成当前必做任务。","只看单项数值，不看资源循环和行动节奏。","一次失败后立刻换完全不同的方向，导致无法积累经验。","在没有理解目标前照抄高阶流派，结果只记住了操作而不知道为什么。","为了追求完美开局反复重开，错过了通过完整回合积累判断的机会。"],checklist:["我能用一句话解释本作的核心循环。","我知道当前最重要的资源是什么，以及它的主要来源和用途。","我知道遇到卡关时至少有两种改变局面的办法。","我能完成一轮基础流程，而不需要每一步都查攻略。","我给下一轮设定了一个具体、可验证的小目标。"],sources:[{title:g.title+" · Steam 商店页",url:g.sourceUrl}],note:"当前使用本地经验型攻略模板。配置 OPENAI_API_KEY 后，可为具体版本、流派和目标联网核查。"};}
